apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: node-4
      containers:
        - name: backend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8116
              hostPort: 8116
              name: http
      volumes:
        - name: sessions
          emptyDir: {}
