apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: node-4
      containers:
        - name: frontend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              hostPort: 3017
              name: http
