apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/aleckarfonta/electroplating/backend
    newName: electroplating-backend
    newTag: local
  - name: ghcr.io/aleckarfonta/electroplating/frontend
    newName: electroplating-frontend
    newTag: local

patches:
  - path: delete-ingress.yaml
  - path: delete-pvc.yaml
  - path: configmap-patch.yaml
  - path: backend-patch.yaml
  - path: frontend-patch.yaml
