apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/aleckarfonta/electroplating/plateforge
    newName: ghcr.io/aleckarfonta/electroplating/plateforge
    newTag: latest

patches:
  - path: ingress-patch.yaml
