apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: plateforge

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: plateforge
    includeSelectors: false

resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - backend.yaml
  - ingress.yaml
