apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plateforge-sessions
  labels:
    app.kubernetes.io/name: plateforge
    app.kubernetes.io/part-of: plateforge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
